import React from 'react';
import './ClinicalSummary.css';

const CLINICAL_INFO = {
  glioma: {
    description: 'Gliomas originate from glial cells and are among the most common primary brain tumors. They vary significantly in aggressiveness — Grade I/II are low-grade while Grade III/IV (Glioblastoma) are highly malignant.',
    recommendation: 'Immediate MRI contrast-enhancement study and neuросurgical consultation recommended. Biopsy may be required for histological grading.',
    urgency: 'high',
  },
  meningioma: {
    description: 'Meningiomas arise from the meninges (the membranes surrounding the brain and spinal cord). Most are benign (WHO Grade I) and slow-growing, but can compress surrounding brain tissue.',
    recommendation: 'Follow-up MRI in 3–6 months suggested. Surgical evaluation if symptomatic or showing rapid growth. Most cases are managed with watchful waiting.',
    urgency: 'medium',
  },
  pituitary: {
    description: 'Pituitary tumors form in the pituitary gland at the base of the brain. Most are benign adenomas but can affect hormone production and compress the optic chiasm.',
    recommendation: 'Endocrinological evaluation and hormonal panel tests advised. MRI with gadolinium contrast and ophthalmological assessment for visual field defects.',
    urgency: 'medium',
  },
  notumor: {
    description: 'No significant intracranial mass lesion detected in this scan. The image characteristics are consistent with normal brain parenchyma within the resolution and classification limits of this model.',
    recommendation: 'No immediate action required based on this scan. Continued monitoring as per the treating clinician\'s standard protocol. This AI analysis is not a substitute for radiological review.',
    urgency: 'low',
  },
};

const URGENCY_CONFIG = {
  high:   { label: 'High Priority', color: 'var(--danger)',  bg: 'var(--danger-glow)', icon: '🔴' },
  medium: { label: 'Medium Priority', color: 'var(--warn)',  bg: 'rgba(255,165,2,0.12)', icon: '🟠' },
  low:    { label: 'Low Priority',  color: 'var(--safe)',   bg: 'var(--safe-glow)',   icon: '🟢' },
};

export default function ClinicalSummary({ diagnosis, confidence, uncertainty, is_anomaly }) {
  const info = CLINICAL_INFO[diagnosis] || CLINICAL_INFO.notumor;
  const urgency = URGENCY_CONFIG[info.urgency];

  return (
    <div className="clinical glass-card animate-fadeUp-d3">
      <div className="clinical__header">
        <div>
          <p className="section-label">Clinical Summary</p>
          <h3 className="clinical__title">AI Interpretation Report</h3>
        </div>
        <span
          className="clinical__urgency"
          style={{ color: urgency.color, background: urgency.bg, border: `1px solid ${urgency.color}44` }}
        >
          {urgency.icon} {urgency.label}
        </span>
      </div>

      <div className="divider" />

      <div className="clinical__row">
        <span className="clinical__row-key">Predicted Class</span>
        <span className="clinical__row-val mono">{diagnosis.toUpperCase()}</span>
      </div>
      <div className="clinical__row">
        <span className="clinical__row-key">Confidence Score</span>
        <span className="clinical__row-val mono">{(confidence * 100).toFixed(2)}%</span>
      </div>
      <div className="clinical__row">
        <span className="clinical__row-key">Uncertainty (Entropy)</span>
        <span className="clinical__row-val mono" style={{ color: is_anomaly ? 'var(--danger)' : undefined }}>
          {uncertainty.toFixed(4)} {is_anomaly ? '⚠' : '✓'}
        </span>
      </div>

      <div className="divider" />

      <div className="clinical__block">
        <h4 className="clinical__block-title">About This Finding</h4>
        <p className="clinical__block-text">{info.description}</p>
      </div>

      <div className="clinical__recommendation">
        <h4 className="clinical__rec-title">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
            <polyline points="22 4 12 14.01 9 11.01"/>
          </svg>
          Suggested Next Steps
        </h4>
        <p className="clinical__block-text">{info.recommendation}</p>
      </div>

      {/* Disclaimer */}
      <div className="clinical__disclaimer">
        ⚕ This analysis is generated by an AI model and is intended for research and decision-support purposes only. It does not constitute a medical diagnosis. Always consult a qualified radiologist or neurologist before clinical decisions.
      </div>
    </div>
  );
}
